### ISSUE TITLE
Consider making task.labels a tuple or set

### ISSUE THREAD

**Issue by eswan18** [Garee/pytodoist#34]
I encountered a strange bug in my code when trying to update a task's labels.

```python
new_label_id = 1234
task.labels.append(new_label_id)
task.update()
```

Naively, I assumed that this would add my new label (1234) to the task, but in the Todoist interface, that didn't happen. Because pytodoist tracks new changes via `__setattr__`, updating a mutable object (like a list) doesn't get caught and stored in the `to_update` attribute. I would think beginner Python users might never figure out the reasoning for why this fails.

If `task.labels` were a tuple or set, on the other hand, the user would have to overwrite it with a new object and the update would be caught in the `__setattr__` call.

There may be other mutable attributes in pytodoist that I haven't encountered yet, but I'd assume they're all susceptible to this problem.

**Comment by eswan18** [comment]
Should have mentioned this in my initial issue post, but this is a **fantastic** library that I wish I'd found earlier. Such an enormous improvement over the simple Doist API. Plus the library design is very elegant. Really appreciate this!

**Comment by Garee** [comment]
Thanks for the bug report and kind words @eswan18.

**Comment by 5t4cktr4c3** [comment]
I just started using `PyTodoist`, however, when working with labels of tasks I expect that the `task.labels` returns a list, tuple, or whatever containing actual `Label` objects and not just the label id. I noticed that the documentation states that the attribute return 'A list of attached label names', which is not the case.
Probably it might be a worthy improvement to link the labels directly to the task and vice versa, so that a label's tasks can be accessed via `label.tasks`.
